spring.application.name=Incident-Management-Platform

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=*


#Local redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

#redislabs
spring.data.redis.host=birthday-bike-birthday-13243.db.redis.io
spring.data.redis.port=16251
spring.data.redis.password=QIO3lqDfazKqKcQ5adaDQFc3A7sdOXBT

spring.cache.type=redis